# Title: Sorting and Algorithm Efficiency
# Author: Cemhan Kaan Özaltan
# ID: 21902695
# Section: 3
# Assignment: 1
# Description: This is the Makefile for compiling the given files

hw1: sorting.cpp main.cpp
	g++ sorting.cpp main.cpp -o hw1