# Title: Binary Search Trees
# Author: Cemhan Kaan Özaltan
# ID: 21902695
# Section: 3
# Assignment: 2
# Description: This is the Makefile for compiling the given files

hw2: BinaryNode.cpp BinarySearchTree.cpp main.cpp
	g++ BinaryNode.cpp BinarySearchTree.cpp main.cpp -o hw2
