# Title: Heaps
# Author: Cemhan Kaan Özaltan
# ID: 21902695
# Section: 3
# Assignment: 3
# Description: This is the Makefile for compiling the given files

simulator: MaxHeap.cpp PrintRequest.cpp Printer.cpp simulator.cpp main.cpp
	g++ MaxHeap.cpp PrintRequest.cpp Printer.cpp simulator.cpp main.cpp -o simulator